'use strict';
/* Small dependency-free WebGL renderer. Runs directly from index.html, offline. */
(()=>{
const $=id=>document.getElementById(id), {keys,spells,GameRules}=SealGameCore;
const rules=new GameRules();
const canvas=$('world'), gl=canvas.getContext('webgl',{antialias:true,alpha:false});
if(!gl){$('errorScreen').classList.remove('hidden');$('errorScreen').textContent='Trình duyệt chưa hỗ trợ WebGL. Hãy mở index.html bằng Chrome hoặc Edge có tăng tốc đồ họa.';return;}
const PI=Math.PI, clamp=(v,a,b)=>Math.max(a,Math.min(b,v)), mix=(a,b,t)=>a+(b-a)*t;
const vadd=(a,b)=>a.map((x,i)=>x+b[i]), vsub=(a,b)=>a.map((x,i)=>x-b[i]), vmul=(a,t)=>a.map(x=>x*t), vlen=a=>Math.hypot(...a), vnorm=a=>vmul(a,1/(vlen(a)||1));
const dot=(a,b)=>a.reduce((s,x,i)=>s+x*b[i],0), cross=(a,b)=>[a[1]*b[2]-a[2]*b[1],a[2]*b[0]-a[0]*b[2],a[0]*b[1]-a[1]*b[0]];
function identity(){return new Float32Array([1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1]);}
function multiply(a,b){const r=new Float32Array(16);for(let c=0;c<4;c++)for(let row=0;row<4;row++)for(let k=0;k<4;k++)r[c*4+row]+=a[k*4+row]*b[c*4+k];return r;}
function matrix(p=[0,0,0],r=[0,0,0],s=[1,1,1]){const [x,y,z]=r,cx=Math.cos(x),sx=Math.sin(x),cy=Math.cos(y),sy=Math.sin(y),cz=Math.cos(z),sz=Math.sin(z);const m=new Float32Array([cz*cy,sz*cy,-sy,0,cz*sy*sx-sz*cx,sz*sy*sx+cz*cx,cy*sx,0,cz*sy*cx+sz*sx,sz*sy*cx-cz*sx,cy*cx,0,...p,1]);for(let col=0;col<3;col++)for(let row=0;row<3;row++)m[col*4+row]*=s[col];return m;}
function inverseRigid(m){const out=identity();for(let c=0;c<3;c++)for(let r=0;r<3;r++)out[c*4+r]=m[r*4+c];for(let r=0;r<3;r++)out[12+r]=-(out[r]*m[12]+out[4+r]*m[13]+out[8+r]*m[14]);return out;}
function perspective(aspect){const f=1/Math.tan(PI*68/360),n=.05,far=220;return new Float32Array([f/aspect,0,0,0,0,f,0,0,0,-.14,(far+n)/(n-far),-1,0,0,2*far*n/(n-far),0]);}
function shader(type,source){const s=gl.createShader(type);gl.shaderSource(s,source);gl.compileShader(s);if(!gl.getShaderParameter(s,gl.COMPILE_STATUS))throw Error(gl.getShaderInfoLog(s));return s;}
function program(v,f){const p=gl.createProgram();gl.attachShader(p,shader(gl.VERTEX_SHADER,v));gl.attachShader(p,shader(gl.FRAGMENT_SHADER,f));gl.linkProgram(p);if(!gl.getProgramParameter(p,gl.LINK_STATUS))throw Error(gl.getProgramInfoLog(p));return p;}
const prog=program(
 'attribute vec3 position; attribute vec3 normal; uniform mat4 model;uniform mat4 vp;varying vec3 N;varying vec3 W;void main(){vec4 world=model*vec4(position,1.);W=world.xyz;N=normalize(mat3(model)*normal);gl_Position=vp*world;}',
 'precision mediump float; varying vec3 N;varying vec3 W;uniform vec3 color;uniform vec3 eye;uniform float emission;uniform float alpha;void main(){vec3 n=normalize(N);float light=max(dot(n,normalize(vec3(-.45,.8,.35))),0.);vec3 shade=color*(vec3(.42,.44,.43)+light*vec3(.69,.50,.30));shade=mix(shade,color*1.35,emission);float fog=1.-exp(-length(W-eye)*.010);vec3 fogColor=mix(vec3(.67,.59,.49),vec3(.90,.66,.48),clamp((W.y+2.)/35.,0.,1.));gl_FragColor=vec4(mix(shade,fogColor,fog*(1.-emission*.75)),alpha);}'
);
const loc={};for(const n of ['position','normal'])loc[n]=gl.getAttribLocation(prog,n);for(const n of ['model','vp','color','eye','emission','alpha'])loc[n]=gl.getUniformLocation(prog,n);
function geometry(vertices){const data=[];for(let i=0;i<vertices.length;i+=9){const a=vertices.slice(i,i+3),b=vertices.slice(i+3,i+6),c=vertices.slice(i+6,i+9),n=vnorm(cross(vsub(b,a),vsub(c,a)));for(let k=0;k<3;k++)data.push(...vertices.slice(i+k*3,i+k*3+3),...n);}const buffer=gl.createBuffer();gl.bindBuffer(gl.ARRAY_BUFFER,buffer);gl.bufferData(gl.ARRAY_BUFFER,new Float32Array(data),gl.STATIC_DRAW);return {buffer,count:data.length/6};}
const box=(()=>{const p=[[-.5,-.5,-.5],[.5,-.5,-.5],[.5,.5,-.5],[-.5,.5,-.5],[-.5,-.5,.5],[.5,-.5,.5],[.5,.5,.5],[-.5,.5,.5]];const faces=[[4,5,6,7],[1,0,3,2],[0,4,7,3],[5,1,2,6],[3,7,6,2],[0,1,5,4]];return geometry(faces.flatMap(f=>[f[0],f[1],f[2],f[0],f[2],f[3]].flatMap(i=>p[i])));})();
function cylinder(segments=12,top=1){const data=[];for(let i=0;i<segments;i++){const a=i/segments*PI*2,b=(i+1)/segments*PI*2,lo=[Math.cos(a),-.5,Math.sin(a)],lob=[Math.cos(b),-.5,Math.sin(b)],hi=[Math.cos(a)*top,.5,Math.sin(a)*top],hib=[Math.cos(b)*top,.5,Math.sin(b)*top];data.push(...lo,...hib,...lob,...lo,...hi,...hib,...hi,0,.5,0,...hib,...lob,0,-.5,0,...lo);}return geometry(data);}
function sphere(seg=10,rings=7){const data=[],p=(i,j)=>{const a=i/seg*PI*2,b=j/rings*PI;return [Math.sin(b)*Math.cos(a),Math.cos(b),Math.sin(b)*Math.sin(a)];};for(let j=0;j<rings;j++)for(let i=0;i<seg;i++){data.push(...p(i,j),...p(i+1,j),...p(i+1,j+1),...p(i,j),...p(i+1,j+1),...p(i,j+1));}return geometry(data);}
const shapes={box,cylinder:cylinder(),cone:cylinder(7,0),sphere:sphere(),rock:sphere(7,5)};
function rgb(hex){return [(hex>>16&255)/255,(hex>>8&255)/255,(hex&255)/255];}
const palette={ground:0x899188,stone:0x9caba1,wood:0x654836,red:0xb45537,skin:0xe5b88f,skinDark:0xc19170,sleeve:0x35484b,glove:0x3d4947,green:0x657b68};
const world=[],particles=[],shots=[],targets=[],hands=[];
function mesh(shape,color,p=[0,0,0],s=[1,1,1],r=[0,0,0],list=world,emission=0){const m={geometry:shapes[shape],color:rgb(color),p:[...p],s:[...s],r:[...r],children:[],emission,alpha:1,visible:true};if(list)list.push(m);return m;}
function group(p=[0,0,0],r=[0,0,0],list=world){const g={p:[...p],r:[...r],s:[1,1,1],children:[],visible:true};if(list)list.push(g);return g;}
let seed=1681;function rand(){seed=(seed*1664525+1013904223)>>>0;return seed/4294967296;}function range(a,b){return a+(b-a)*rand();}
mesh('box',palette.ground,[0,-.25,-10],[90,.5,110]);
// A broad stone path leads to the training gate.
for(let z=8;z>-30;z-=3)for(let x=-1;x<=1;x++)mesh('box',x===0?0xa5ada1:0x9da89c,[x*2.1,-.025,z+range(-.12,.12)],[1.95,.12,2.65],[0,range(-.025,.025),0]);
for(let i=0;i<35;i++){let x=range(-22,22),z=range(-36,18);if(Math.abs(x)<4)continue;mesh('rock',0x86988b,[x,.12,z],[range(.3,.85),range(.18,.35),range(.3,.8)],[0,range(0,PI),0]);}
// Low-poly canyon walls and distant ridges.
for(let side of [-1,1])for(let i=0;i<17;i++){let h=range(5,13);mesh('rock',i%3?0x7b8c80:0x9c9a83,[side*range(25,40),h*.46,-48+i*5],[range(5,10),h,range(5,9)],[0,range(0,PI),.05*side]);}
for(let i=0;i<15;i++)mesh('cone',0x929786,[(i-7)*10,range(5,9),-78],[range(7,14),range(17,29),range(6,12)],[0,range(0,PI),0]);
// Torii gate, layered roof and subtle gold braces.
for(const x of [-8,8]){mesh('cylinder',palette.red,[x,3.6,-24],[.43,7.2,.43]);mesh('cylinder',0x3c4843,[x,.32,-24],[.66,.65,.66]);mesh('box',0xa59b80,[x,7,-24],[1.5,.22,1.2]);}
mesh('box',palette.red,[0,6.7,-24],[19,.48,.55]);mesh('box',0x364846,[0,7.3,-24],[21,.43,1.3]);mesh('box',palette.red,[0,5.3,-24],[17,.3,.45]);mesh('box',0xc79654,[0,6,-23.67],[1.25,1.55,.1]);mesh('box',0x3e4741,[0,6,-23.57],[.92,1.22,.05]);
for(const side of [-1,1])mesh('box',0x364846,[side*10.7,7.5,-24],[1.5,.4,1.3],[0,0,side*.24]);
for(let x=-8;x<=8;x+=2)mesh('box',0x90583d,[x,6.1,-24],[.14,1.5,.2]);
// Timber perimeter rails.
for(let side of [-1,1]){for(let i=0;i<9;i++)mesh('box',0x776f54,[side*16,1,-24+i*4],[.32,2,.32]);for(let y of [.6,1.4])mesh('box',0x91856a,[side*16,y,-8],[.18,.18,34]);}
function tree(x,z,h){mesh('cylinder',0x6a5845,[x,h*.4,z],[.19,h*.8,.19]);for(let j=0;j<3;j++){const size=h*(.35-j*.07);mesh('cone',j===0?0x496b60:j===1?0x5b7d66:0x718972,[x,h*(.46+j*.19),z],[size,h*.56,size],[0,j*.45,0]);}mesh('cylinder',0x657968,[x,.012,z],[h*.42,.016,h*.42]);}
for(let side of [-1,1])for(let i=0;i<17;i++)tree(side*range(18,25),range(-51,13),range(4,8));
function lantern(x,z){mesh('box',0x73877d,[x,.15,z],[1.25,.3,1.25]);mesh('box',0x929b87,[x,.7,z],[.42,1,.42]);mesh('box',0x909d88,[x,1.22,z],[1.04,.18,1.04]);mesh('box',0xffb360,[x,1.62,z],[.63,.68,.63],[0,0,0],world,.85);for(let a=0;a<4;a++){let angle=a/4*PI*2+PI/4;mesh('box',0x5c6d60,[x+Math.cos(angle)*.44,1.63,z+Math.sin(angle)*.44],[.12,.8,.12]);}mesh('cone',0x617a6d,[x,2.25,z],[1,.7,1],[0,PI/4,0]);mesh('sphere',0x617a6d,[x,2.7,z],[.16,.2,.16]);}
for(const x of [-5,5])for(const z of [4,-19])lantern(x,z);
// Banners beside the gate.
for(const side of [-1,1]){mesh('cylinder',0x5b6550,[side*12,2.7,-22],[.08,5.4,.08]);mesh('box',0x5b6550,[side*11.4,5.2,-22],[1.5,.08,.08]);mesh('box',0xba7050,[side*11.4,3.9,-22],[1.2,2.7,.035]);mesh('box',0xe1b47d,[side*11.4,3.9,-21.97],[.55,1.25,.02]);}
// Grass tufts away from the path.
for(let i=0;i<110;i++){let x=range(-19,19),z=range(-32,15);if(Math.abs(x)<3)continue;for(let j=0;j<2;j++)mesh('cone',i%2?0x83927b:0x6d8772,[x+j*.12,.15,z],[.11,range(.3,.55),.08],[0,range(0,PI),range(-.2,.2)]);}
const spawnPositions=[[-6,1.72,-8],[0,1.72,-12],[6,1.72,-9],[-8,1.72,-20],[8,1.72,-20]];
function makeTarget(pos,i){const g=group([pos[0],0,pos[2]]);const add=(shape,color,p,s,r=[0,0,0])=>mesh(shape,color,p,s,r,g.children);add('box',0x524b3c,[0,.07,0],[1.3,.14,1.1]);add('box',0x997b55,[0,.88,0],[.22,1.7,.22]);add('box',0x987a54,[0,1.4,0],[1.6,.15,.16]);const disc=add('cylinder',0xdfcc9d,[0,pos[1],.03],[.77,.14,.77],[PI/2,0,0]);add('cylinder',0xb76240,[0,pos[1],.112],[.60,.035,.60],[PI/2,0,0]);add('cylinder',0xe1d2ad,[0,pos[1],.137],[.42,.02,.42],[PI/2,0,0]);add('cylinder',0xa15336,[0,pos[1],.153],[.22,.018,.22],[PI/2,0,0]);add('cylinder',0xf9c77c,[0,pos[1],.168],[.066,.019,.066],[PI/2,0,0]);return {g,disc,pos:[pos[0],pos[1],pos[2]+.1],hp:100,max:100,index:i,hit:0,dead:false};}
spawnPositions.forEach((p,i)=>targets.push(makeTarget(p,i)));
// Camera-mounted hands: palms, five fingers with three articulated segments.
const handRoot=group([0,0,0],[0,0,0],null);
function buildHand(side){const h=group([side*.4,-.37,-.65],[.0,0,side*.3],handRoot.children);const add=(shape,color,p,s,r=[0,0,0],list=h.children)=>mesh(shape,color,p,s,r,list);add('box',palette.sleeve,[0,-.28,.08],[.16,.37,.18],[.15,0,0]);add('box',0x253839,[0,-.14,.06],[.18,.09,.19]);add('box',0x8e9e8b,[0,-.105,.065],[.184,.028,.192]);add('box',palette.skin,[0,0,0],[.142,.21,.072]);add('box',palette.glove,[0,-.03,.041],[.15,.12,.026]);add('box',0x73827b,[0,-.027,.058],[.075,.073,.007]);const fingerGroups=[];const lengths=[.105,.12,.112,.092];for(let i=0;i<4;i++){const f=group([(i-1.5)*.036,.097,0],[0,0,0],h.children);let parent=f;const parts=[];for(let j=0;j<3;j++){const length=lengths[i]*(j===0?.48:j===1?.31:.27);const joint=j===0?f:group([0,parts[j-1].len,0],[0,0,0],parent.children);mesh('box',palette.skin,[0,length/2,0],[.03,length,.038],[0,0,0],joint.children);mesh('sphere',palette.skinDark,[0,0,0],[.017,.017,.02],[0,0,0],joint.children);if(j===2)mesh('box',0xf0cdae,[0,length*.65,-.021],[.02,length*.48,.003],[0,0,0],joint.children);parts.push({joint,len:length});parent=joint;}fingerGroups.push({root:f,parts});}const thumb=group([-side*.075,.002,0],[0,0,side*.75],h.children);mesh('box',palette.skin,[0,.028,0],[.04,.061,.048],[0,0,0],thumb.children);const tip=group([0,.058,0],[.15,0,0],thumb.children);mesh('box',palette.skin,[0,.025,0],[.036,.05,.042],[0,0,0],tip.children);hands.push({side,h,fingers:fingerGroups,thumb,thumbTip:tip});}
buildHand(-1);buildHand(1);
// Pose names describe the reference image rather than claim canonical Naruto seals.
const names=['Mỏ nhọn','Tai kép','Trụ thẳng','Móc tay','Chụm ngang','Song chỉ','Xòe chéo','Khóa ngón','Vòng cung','Chắp nghiêng','Mở lòng','Cuộn tay'];
const poses=[
 {p:[.19,-.27,-.67],r:[.18,.55,.62],curl:[.08,.08,1.3,1.4],spread:.06,thumb:.5},
 {p:[.16,-.28,-.68],r:[.35,.3,.4],curl:[0,0,1.7,1.7],spread:.21,thumb:1.1},
 {p:[.08,-.23,-.67],r:[.0,.05,.04],curl:[0,0,0,0],spread:0,thumb:.2},
 {p:[.20,-.28,-.66],r:[.75,.2,1.35],curl:[1.45,.55,1.45,1.45],spread:.05,thumb:.7},
 {p:[.08,-.31,-.65],r:[.85,.2,1.4],curl:[.22,.3,.4,.5],spread:.06,thumb:1.15},
 {p:[.18,-.29,-.7],r:[.7,.5,1.2],curl:[.1,.1,1.7,1.7],spread:.1,thumb:.5},
 {p:[.21,-.28,-.72],r:[.4,.0,.6],curl:[.0,.15,.4,.9],spread:.24,thumb:1.2},
 {p:[.045,-.29,-.68],r:[.45,.6,.45],curl:[.2,1.3,1.4,1.4],spread:0,thumb:.25},
 {p:[.17,-.28,-.65],r:[1.05,.3,.5],curl:[1.2,.12,.22,.4],spread:.19,thumb:.1},
 {p:[.055,-.28,-.7],r:[.14,.1,.18],curl:[.15,.22,.25,.35],spread:.07,thumb:.55},
 {p:[.19,-.29,-.69],r:[.3,.4,.45],curl:[1.0,.1,.3,.55],spread:.24,thumb:.05},
 {p:[.12,-.3,-.65],r:[1.1,.6,.7],curl:[1.1,1.6,1.7,1.7],spread:.05,thumb:1.0}
];
let activePose=-1,poseAge=99,animationTime=0,started=false,paused=false,won=false,round=1,selected=0,score=0;
let camera={p:[0,1.72,7],yaw:0,pitch:0};let pressed=new Set(),drag=false,lastMouse=[0,0],lastTime=0,breathTime=0,breathTick=0,recoil=0,hitTimer=0,flashTimer=0,messageTime=0,muted=false,audio=null;
// UI built from the same seal and spell data used by the rule engine.
$('sealKeys').innerHTML=keys.map((key,i)=>'<button class="seal" data-key="'+key+'" title="'+key.toUpperCase()+' — Ấn '+String(i+1).padStart(2,'0')+': '+names[i]+'" aria-label="Ấn '+(i+1)+', phím '+key+'"><span class="thumb" style="background-position:'+(i%3*50)+'% '+(Math.floor(i/3)*25)+'%"></span><span class="seal-key">'+key.toUpperCase()+'</span><small>'+String(i+1).padStart(2,'0')+'</small></button>').join('');
$('spellList').innerHTML=spells.map((s,i)=>'<button class="spell '+(i===0?'selected':'')+'" data-spell="'+i+'"><span class="spell-icon">'+['火','炎','焱'][i]+'</span><div><div class="spell-title">'+s.name+'<small>'+s.cost+' CHAKRA</small></div><p>'+s.subtitle+'</p><div class="spell-sequence">'+s.sequence.map(k=>'<kbd data-seq="'+k+'">'+k.toUpperCase()+'</kbd>').join('')+'</div></div></button>').join('');
function selectSpell(i){selected=i;document.querySelectorAll('.spell').forEach((el,j)=>el.classList.toggle('selected',i===j));updateUI();}
function announce(text,error=false){$('message').textContent=text;$('message').style.color=error?'#ffc28b':'#c7d5bb';messageTime=3.2;}
function updateUI(){const seq=rules.sequence;const matching=spells.findIndex(s=>seq.length&&s.sequence.slice(0,seq.length).join('')===seq.join(''));if(matching>=0&&selected!==matching){selected=matching;document.querySelectorAll('.spell').forEach((el,j)=>el.classList.toggle('selected',j===selected));}const spell=spells[selected];$('comboSlots').innerHTML=spell.sequence.map((k,i)=>'<span class="combo-slot '+(seq[i]===k?'done':seq.length===i?'next':'')+'">'+k.toUpperCase()+'</span>').join('');$('comboLabel').textContent=rules.ready()?'ẤN HOÀN CHỈNH • '+rules.ready().name.toUpperCase():spell.name.toUpperCase()+' ／ '+seq.length+' / 4 ẤN';$('castButton').disabled=!started||paused||won||!rules.ready()||rules.cooldown>0||rules.chakra<spell.cost;document.querySelectorAll('.seal').forEach(el=>{el.classList.toggle('active',el.dataset.key===keys[activePose]);el.classList.toggle('pending',seq.includes(el.dataset.key));});document.querySelectorAll('.spell').forEach((el,i)=>el.querySelectorAll('kbd').forEach((k,j)=>k.classList.toggle('done',i===selected&&seq[j]===k.dataset.seq)));}
function initAudio(){if(audio)return;try{audio=new(window.AudioContext||window.webkitAudioContext)();}catch{muted=true;}}
function tone(freq=260,duration=.08,type='sine',volume=.06){if(muted||!audio)return;const o=audio.createOscillator(),g=audio.createGain();o.type=type;o.frequency.setValueAtTime(freq,audio.currentTime);o.frequency.exponentialRampToValueAtTime(freq*.65,audio.currentTime+duration);g.gain.setValueAtTime(volume,audio.currentTime);g.gain.exponentialRampToValueAtTime(.0001,audio.currentTime+duration);o.connect(g).connect(audio.destination);o.start();o.stop(audio.currentTime+duration);}
function fireSound(){if(muted||!audio)return;const size=audio.sampleRate*.65,buffer=audio.createBuffer(1,size,audio.sampleRate),data=buffer.getChannelData(0);for(let i=0;i<size;i++)data[i]=(Math.random()*2-1)*(1-i/size);const src=audio.createBufferSource(),filter=audio.createBiquadFilter(),gain=audio.createGain();src.buffer=buffer;filter.type='lowpass';filter.frequency.setValueAtTime(1500,audio.currentTime);filter.frequency.exponentialRampToValueAtTime(180,audio.currentTime+.6);gain.gain.value=.26;src.connect(filter).connect(gain).connect(audio.destination);src.start();}
function seal(key){if(!started||paused||won)return;const result=rules.seal(key);activePose=keys.indexOf(key);poseAge=0;$('currentSeal').textContent=key.toUpperCase()+' ／ Ấn '+String(activePose+1).padStart(2,'0')+' · '+names[activePose];tone(290+activePose*28,.09,'triangle');if(!result.valid)announce('Sai chuỗi — bắt đầu lại bằng '+spells[selected].sequence[0].toUpperCase(),true);else if(result.ready){announce('Chakra đã tụ. Ngắm bia và nhấn SPACE.');tone(670,.23,'sine',.045);}else announce('Ấn '+rules.sequence.length+' / 4 — tiếp tục kết ấn');updateUI();}
function aim(){const cp=Math.cos(camera.pitch);return [-Math.sin(camera.yaw)*cp,Math.sin(camera.pitch),-Math.cos(camera.yaw)*cp];}
function fireShot(pos,dir,speed,size,damage,type){shots.push({p:[...pos],old:[...pos],v:vmul(dir,speed),size,damage,type,life:type==='breath'?.8:3,trail:0});}
function cast(){if(!started||paused||won)return;const result=rules.cast();if(!result.ok){announce({sequence:'Chưa đủ ấn — kết đúng chuỗi trước khi thi triển.',cooldown:'Chờ một nhịp để thi triển tiếp.',chakra:'Chakra chưa đủ — chờ hồi phục.'}[result.reason],true);tone(130,.1,'sine');return;}const d=aim(),p=vadd(camera.p,vmul(d,.8));activePose=-1;poseAge=0;recoil=.2;flashTimer=.16;fireSound();announce(result.spell.name+'!');if(result.spell.id==='ball')fireShot(p,d,22,.42,result.spell.damage,'ball');else if(result.spell.id==='phoenix'){const right=[Math.cos(camera.yaw),0,-Math.sin(camera.yaw)];for(let i=-2;i<=2;i++)fireShot(p,vnorm(vadd(d,vmul(right,i*.07))),25,.21,35,'phoenix');}else{breathTime=1.5;breathTick=0;}updateUI();}
function hit(target,damage,pos){if(target.dead)return;target.hp=Math.max(0,target.hp-damage);target.hit=.2;hitTimer=.14;burst(pos,12,.75);tone(110,.07,'triangle',.04);if(target.hp===0){target.dead=true;score++;burst(target.pos,34,1.8);$('score').textContent=String(score).padStart(2,'0');announce('Bia '+(target.index+1)+' đã hạ!');if(score===5){won=true;pressed.clear();releasePointer();$('winStats').textContent='Bạn đã hạ 5 bia với '+rules.casts+' lần thi triển. Tiếp tục để luyện ngắm và kết ấn.';setTimeout(()=>{if(won)$('winScreen').classList.remove('hidden');},650);}}}
function particle(p,v,size=.06,life=.7,color=0xffa34d){if(particles.length>420)return;particles.push({p:[...p],v:[...v],size,life,max:life,color:rgb(color)});}
function burst(pos,count,speed){for(let i=0;i<count;i++)particle(pos,[range(-speed,speed),range(.2,speed*1.2),range(-speed,speed)],range(.025,.1),range(.4,.95),i%3?0xff9943:0xffdb86);}
function updateShots(dt){for(let i=shots.length-1;i>=0;i--){const shot=shots[i];shot.old=[...shot.p];shot.p=vadd(shot.p,vmul(shot.v,dt));shot.life-=dt;shot.trail+=dt;while(shot.trail>.025){shot.trail-=.025;particle(shot.p,vmul(shot.v,-.06),shot.size*.4,.3,0xffad58);}let collided=false;for(const target of targets){if(target.dead)continue;const delta=vsub(shot.p,shot.old),toTarget=vsub(target.pos,shot.old),t=clamp(dot(toTarget,delta)/(dot(delta,delta)||1),0,1),closest=vadd(shot.old,vmul(delta,t));if(vlen(vsub(closest,target.pos))<.74+shot.size){hit(target,shot.damage,closest);collided=true;break;}}if(collided||shot.life<0||shot.p[1]<.08||Math.abs(shot.p[0])>30||shot.p[2]<-45){if(!collided&&shot.life>0)burst(shot.p,10,.9);shots.splice(i,1);}}}
function updateParticles(dt){for(let i=particles.length-1;i>=0;i--){const p=particles[i];p.life-=dt;if(p.life<=0){particles.splice(i,1);continue;}p.p=vadd(p.p,vmul(p.v,dt));p.v[1]+=dt*.35;p.v=vmul(p.v,1-dt*.8);}}
function updateHands(dt){const speed=1-Math.exp(-dt*17),pose=poses[activePose];for(const h of hands){const side=h.side;const p=pose?pose.p:[.38,-.42,-.62],r=pose?pose.r:[.18,.15,.35];for(let i=0;i<3;i++){const target=i===0?p[0]*side:i===1?p[1]+Math.sin(animationTime*1.8)*.004:p[2]+recoil*.6;h.h.p[i]=mix(h.h.p[i],target,speed);h.h.r[i]=mix(h.h.r[i],r[i]*(i===0?1:side),speed);}for(let i=0;i<4;i++){const finger=h.fingers[i],curl=pose?pose.curl[side<0?i:3-i]:.3;finger.root.r[2]=mix(finger.root.r[2],(i-1.5)*(pose?pose.spread:.08)*side,speed);for(let j=0;j<3;j++)finger.parts[j].joint.r[0]=mix(finger.parts[j].joint.r[0],curl*(j===0?.65:1),speed);}h.thumb.r[0]=mix(h.thumb.r[0],pose?pose.thumb:.2,speed);h.thumb.r[2]=mix(h.thumb.r[2],side*(pose?.5:.95),speed);h.thumbTip.r[0]=mix(h.thumbTip.r[0],pose?pose.thumb:.2,speed);}handRoot.p[1]=Math.sin(animationTime*2)*.003;}
function forwardMove(dt){const speed=(pressed.has('Shift')?6:3.7)*dt;let f=(pressed.has('ArrowUp')?1:0)-(pressed.has('ArrowDown')?1:0),r=(pressed.has('ArrowRight')?1:0)-(pressed.has('ArrowLeft')?1:0);if(!f&&!r)return;const length=Math.hypot(f,r);f/=length;r/=length;let nx=camera.p[0]+(-Math.sin(camera.yaw)*f+Math.cos(camera.yaw)*r)*speed,nz=camera.p[2]+(-Math.cos(camera.yaw)*f-Math.sin(camera.yaw)*r)*speed;nx=clamp(nx,-14.5,14.5);nz=clamp(nz,-22,14);if(targets.some(t=>!t.dead&&Math.hypot(nx-t.pos[0],nz-t.pos[2])<1))return;camera.p[0]=nx;camera.p[2]=nz;}
function findAimTarget(){const d=aim();let best=null,bestDist=Infinity;for(const t of targets){if(t.dead)continue;const delta=vsub(t.pos,camera.p),dist=dot(delta,d);if(dist<0)continue;const offset=vlen(vsub(delta,vmul(d,dist)));if(offset<.77&&dist<bestDist){best=t;bestDist=dist;}}return best;}
// Renderer: sky pass, opaque world, transparent fire, then first-person hands.
const skyProg=program('attribute vec2 pos;varying vec2 uv;void main(){uv=pos*.5+.5;gl_Position=vec4(pos,0.,1.);}', 'precision mediump float;varying vec2 uv;uniform float aspect;uniform vec2 sun;void main(){vec3 col=mix(vec3(.86,.70,.52),vec3(.36,.49,.49),pow(uv.y,.7));vec2 d=(uv-sun)*vec2(aspect,1.);float glow=exp(-length(d)*6.);col+=vec3(.22,.13,.06)*glow;float disc=1.-smoothstep(.046,.048,length(d));col=mix(col,vec3(1.,.82,.54),disc*.85);gl_FragColor=vec4(col,1.);}');
const skyBuffer=gl.createBuffer();gl.bindBuffer(gl.ARRAY_BUFFER,skyBuffer);gl.bufferData(gl.ARRAY_BUFFER,new Float32Array([-1,-1,1,-1,-1,1,-1,1,1,-1,1,1]),gl.STATIC_DRAW);const skyLoc={pos:gl.getAttribLocation(skyProg,'pos'),aspect:gl.getUniformLocation(skyProg,'aspect'),sun:gl.getUniformLocation(skyProg,'sun')};
let projection=identity(),aspect=1;
function resize(){const dpr=Math.min(window.devicePixelRatio||1,1.5);canvas.width=Math.round(innerWidth*dpr);canvas.height=Math.round(innerHeight*dpr);aspect=innerWidth/innerHeight;projection=perspective(aspect);gl.viewport(0,0,canvas.width,canvas.height);}window.addEventListener('resize',resize);resize();
function drawMesh(m,parent=identity()){if(!m.visible)return;const model=multiply(parent,matrix(m.p,m.r,m.s));if(m.geometry){gl.bindBuffer(gl.ARRAY_BUFFER,m.geometry.buffer);gl.vertexAttribPointer(loc.position,3,gl.FLOAT,false,24,0);gl.vertexAttribPointer(loc.normal,3,gl.FLOAT,false,24,12);gl.uniformMatrix4fv(loc.model,false,model);gl.uniform3fv(loc.color,m.color);gl.uniform1f(loc.emission,m.emission||0);gl.uniform1f(loc.alpha,m.alpha||1);gl.drawArrays(gl.TRIANGLES,0,m.geometry.count);}for(const child of m.children)drawMesh(child,model);}
const effectMesh=mesh('rock',0xff923e,[0,0,0],[1,1,1],[0,0,0],null,1);
function drawEffect(p,size,color,alpha=1){effectMesh.p=p;effectMesh.s=[size,size,size];effectMesh.color=color;effectMesh.alpha=alpha;effectMesh.r=[animationTime,animationTime*.7,0];drawMesh(effectMesh);}
function render(){gl.disable(gl.DEPTH_TEST);gl.disable(gl.BLEND);gl.useProgram(skyProg);gl.bindBuffer(gl.ARRAY_BUFFER,skyBuffer);gl.enableVertexAttribArray(skyLoc.pos);gl.vertexAttribPointer(skyLoc.pos,2,gl.FLOAT,false,0,0);gl.uniform1f(skyLoc.aspect,aspect);gl.uniform2f(skyLoc.sun,.72+camera.yaw*.7,.67-camera.pitch*.8);gl.drawArrays(gl.TRIANGLES,0,6);gl.disableVertexAttribArray(skyLoc.pos);gl.enable(gl.DEPTH_TEST);gl.depthFunc(gl.LEQUAL);gl.clear(gl.DEPTH_BUFFER_BIT);gl.useProgram(prog);gl.enableVertexAttribArray(loc.position);gl.enableVertexAttribArray(loc.normal);const cam=matrix(camera.p,[camera.pitch,camera.yaw,0]),vp=multiply(projection,inverseRigid(cam));gl.uniformMatrix4fv(loc.vp,false,vp);gl.uniform3fv(loc.eye,camera.p);for(const m of world)drawMesh(m);gl.enable(gl.BLEND);gl.blendFunc(gl.SRC_ALPHA,gl.ONE);gl.depthMask(false);for(const s of shots){drawEffect(s.p,s.size*1.65,rgb(0xff722f),.12);drawEffect(s.p,s.size,rgb(0xffa53a),.5);drawEffect(s.p,s.size*.52,rgb(0xffe89e),.9);}for(const p of particles)drawEffect(p.p,p.size*(.3+p.life/p.max*.7),p.color,p.life/p.max*.85);gl.depthMask(true);gl.disable(gl.BLEND);gl.clear(gl.DEPTH_BUFFER_BIT);gl.uniformMatrix4fv(loc.vp,false,projection);gl.uniform3fv(loc.eye,[0,0,0]);drawMesh(handRoot);}
function frame(now){const dt=Math.min((now-lastTime)/1000||.016,.045);lastTime=now;animationTime+=dt;let running=started&&!paused&&!won;if(running){const expired=rules.tick(dt);if(expired)announce('Chuỗi ấn hết hạn — kết lại từ đầu.',true);forwardMove(dt);poseAge+=dt;if(poseAge>2.8&&rules.sequence.length===0)activePose=-1;recoil=Math.max(0,recoil-dt);flashTimer=Math.max(0,flashTimer-dt);hitTimer=Math.max(0,hitTimer-dt);if(breathTime>0){breathTime-=dt;breathTick+=dt;while(breathTick>.045){breathTick-=.045;const d=aim(),right=[Math.cos(camera.yaw),0,-Math.sin(camera.yaw)],dir=vnorm(vadd(vadd(d,vmul(right,range(-.09,.09))),[0,range(-.065,.065),0]));fireShot(vadd(camera.p,vmul(d,.65)),dir,13,range(.15,.3),18,'breath');}}updateShots(dt);messageTime-=dt;if(messageTime<=0){$('message').textContent=rules.ready()?(rules.chakra<rules.ready().cost?'Chờ chakra hồi phục...':'Ngắm bia và nhấn SPACE để thi triển'):'Chọn một chuỗi hỏa thuật bên phải';$('message').style.color='#c7c5b6';}updateUI();}
if(!paused){updateParticles(dt);for(const t of targets){t.hit=Math.max(0,t.hit-dt);t.g.r[0]=t.dead?mix(t.g.r[0],-1.5,1-Math.exp(-dt*6)):Math.sin(t.hit*38)*t.hit*.16;if(t.dead)t.g.p[1]=mix(t.g.p[1],-.1,.08);else t.disc.color=rgb(t.hit>0?0xffb56b:0xdfcc9d);}updateHands(dt);}
if(running&&rand()<dt*12)particle([range(-15,15),range(.5,5),range(-25,6)],[.15,.15,.06],.017,3.2,0xffb65c);
$('chakraNumber').textContent=Math.floor(rules.chakra)+' / 100';$('chakraFill').style.width=rules.chakra+'%';$('castCount').textContent=rules.casts+' thuật';$('flash').style.opacity=flashTimer*.65;$('hitMarker').style.opacity=hitTimer>0?1:0;const aimTarget=findAimTarget();$('reticle').classList.toggle('on-target',!!aimTarget);$('targetInfo').style.opacity=aimTarget&&running?1:0;if(aimTarget){$('targetName').textContent='BIA '+String(aimTarget.index+1).padStart(2,'0');$('targetHP').style.width=aimTarget.hp+'%';}render();requestAnimationFrame(frame);}
function requestPointer(){try{const promise=canvas.requestPointerLock?.();promise?.catch?.(()=>announce('Kéo chuột trong sân tập để ngắm.'));}catch{announce('Kéo chuột trong sân tập để ngắm.');}}
function releasePointer(){if(document.pointerLockElement)document.exitPointerLock?.();}
function start(){started=true;paused=false;won=false;document.body.classList.add('playing');document.body.classList.remove('paused');$('startScreen').classList.add('hidden');$('pauseScreen').classList.add('hidden');initAudio();audio?.resume();announce('Hỏa cầu: Q → W → E → R, rồi SPACE.');requestPointer();updateUI();}
function pause(){if(!started||won)return;paused=true;pressed.clear();drag=false;releasePointer();document.body.classList.add('paused');$('pauseScreen').classList.remove('hidden');updateUI();}
function resume(){paused=false;document.body.classList.remove('paused');$('pauseScreen').classList.add('hidden');requestPointer();updateUI();}
function reset(next=false){if(next)round++;Object.assign(rules,new GameRules());score=0;shots.length=0;particles.length=0;pressed.clear();breathTime=0;recoil=0;flashTimer=0;hitTimer=0;camera={p:[0,1.72,7],yaw:0,pitch:0};targets.forEach(t=>{t.hp=t.max;t.dead=false;t.hit=0;t.g.r=[0,0,0];t.g.p[1]=0;});$('score').textContent='00';$('roundText').textContent='Đợt luyện tập '+String(round).padStart(2,'0');$('winScreen').classList.add('hidden');activePose=-1;selected=0;selectSpell(0);start();}
function toggleSound(){muted=!muted;$('soundButton').textContent=muted?'♫̸':'♪';$('soundButton').setAttribute('aria-pressed',String(muted));}
$('startButton').onclick=start;$('resumeButton').onclick=resume;$('resetButton').onclick=()=>reset(false);$('nextButton').onclick=()=>reset(true);$('castButton').onclick=cast;$('soundButton').onclick=toggleSound;$('helpButton').onclick=()=>{$('guide').classList.toggle('hidden');};
document.querySelectorAll('.seal').forEach(el=>el.onclick=()=>seal(el.dataset.key));document.querySelectorAll('.spell').forEach(el=>el.onclick=()=>selectSpell(Number(el.dataset.spell)));
window.addEventListener('keydown',e=>{const key=e.key.toLowerCase();if([' ','backspace','arrowup','arrowdown','arrowleft','arrowright'].includes(key))e.preventDefault();if(e.repeat){if(e.key.startsWith('Arrow'))pressed.add(e.key);return;}if(key==='enter'){if(won)reset(true);else if(!started)start();else if(paused)resume();return;}if(key==='escape'){if(started&&!won&&!paused)pause();return;}if(key==='h'){$('guide').classList.toggle('hidden');return;}if(key==='m'){toggleSound();return;}if(!started||paused||won)return;if(keys.includes(key))seal(key);else if(key===' ')cast();else if(key==='backspace'){rules.clear();activePose=-1;announce('Đã xóa chuỗi ấn.');updateUI();}else if(['1','2','3'].includes(key))selectSpell(Number(key)-1);pressed.add(e.key);});
window.addEventListener('keyup',e=>pressed.delete(e.key));window.addEventListener('blur',()=>{if(started&&!paused&&!won)pause();});document.addEventListener('visibilitychange',()=>{if(document.hidden&&started&&!paused&&!won)pause();});
canvas.addEventListener('mousedown',e=>{if(!started||paused||won)return;drag=true;lastMouse=[e.clientX,e.clientY];if(e.button===0&&document.pointerLockElement!==canvas)requestPointer();});window.addEventListener('mouseup',()=>drag=false);window.addEventListener('mousemove',e=>{if(!started||paused||won)return;const locked=document.pointerLockElement===canvas;if(!locked&&!drag)return;const dx=locked?e.movementX:e.clientX-lastMouse[0],dy=locked?e.movementY:e.clientY-lastMouse[1];lastMouse=[e.clientX,e.clientY];camera.yaw-=dx*.0025;camera.pitch=clamp(camera.pitch-dy*.0025,-.95,.95);});
canvas.addEventListener('touchstart',e=>{if(!started||paused||won)return;drag=true;lastMouse=[e.touches[0].clientX,e.touches[0].clientY];},{passive:true});canvas.addEventListener('touchmove',e=>{if(!drag||paused||won)return;const touch=e.touches[0];camera.yaw-=(touch.clientX-lastMouse[0])*.004;camera.pitch=clamp(camera.pitch-(touch.clientY-lastMouse[1])*.004,-.95,.95);lastMouse=[touch.clientX,touch.clientY];e.preventDefault();},{passive:false});canvas.addEventListener('touchend',()=>drag=false);
let pointerWasLocked=false;document.addEventListener('pointerlockchange',()=>{const locked=document.pointerLockElement===canvas;if(pointerWasLocked&&!locked&&started&&!paused&&!won)pause();pointerWasLocked=locked;});
canvas.addEventListener('webglcontextlost',e=>{e.preventDefault();pause();$('errorScreen').classList.remove('hidden');$('errorScreen').textContent='Kết nối đồ họa bị gián đoạn. Tải lại trang để tiếp tục.';});
updateUI();requestAnimationFrame(frame);
})();
