const fs = require("node:fs");
const path = require("node:path");
const vm = require("node:vm");
const assert = require("node:assert/strict");
const root = path.join(__dirname, "..");
const coreSource = fs.readFileSync(path.join(root, "game-core.js"), "utf8");
const coreContext = {};
vm.runInNewContext(coreSource, coreContext);
const { GameRules, spells, keys } = coreContext.SealGameCore;
assert.equal(new Set(keys).size, 12);
for (const spell of spells) {
  const r2 = new GameRules();
  spell.sequence.forEach((k) => r2.seal(k));
  assert.equal(r2.ready().id, spell.id);
  assert.equal(r2.cast().ok, true);
  assert.equal(r2.chakra, 100 - spell.cost);
  assert.equal(r2.sequence.length, 0);
  assert.equal(r2.casts, 1);
}
const r = new GameRules();
r.seal("q");
r.seal("e");
assert.equal(r.sequence.length, 0);
r.seal("q");
r.seal("w");
r.seal("a");
assert.equal(r.sequence.join(""), "a");
r.tick(7.1);
assert.equal(r.sequence.length, 0);
assert.equal(r.cast().reason, "sequence");
["z", "x", "c", "v"].forEach((k) => r.seal(k));
r.chakra = 59;
assert.equal(r.cast().reason, "chakra");
assert.equal(r.sequence.length, 4);
r.tick(1);
assert.equal(r.cast().ok, true);
["q", "w", "e", "r"].forEach((k) => r.seal(k));
assert.equal(r.cast().reason, "cooldown");
r.tick(1.3);
assert.equal(r.cast().reason, "chakra");
r.tick(2);
assert.equal(r.cast().ok, true);
const binary = fs.readFileSync(path.join(root, "assets/ninja-hands.glb"));
assert.equal(binary.readUInt32LE(0), 1179937895);
assert.equal(binary.readUInt32LE(4), 2);
assert.equal(binary.readUInt32LE(8), binary.length);
const jsonLength = binary.readUInt32LE(12), model = JSON.parse(binary.subarray(20, 20 + jsonLength).toString());
assert.equal(model.skins.length, 1);
assert.equal(model.skins[0].joints.length, 16);
assert.equal(model.animations.length, 12);
for (const animation of model.animations) assert.ok(animation.channels.length >= 12);
assert.ok(model.meshes.some((m) => m.primitives.some((p) => p.attributes.JOINTS_0 !== void 0 && p.attributes.WEIGHTS_0 !== void 0)));
for (const primitive of model.meshes.flatMap((m) => m.primitives)) assert.ok(primitive.attributes.NORMAL !== void 0);
const pkg = JSON.parse(fs.readFileSync(path.join(root, "package.json"), "utf8"));
assert.ok(pkg.dependencies.three);
assert.equal(pkg.version, "0.2.0");
const bundle = fs.readFileSync(path.join(root, "game.js"), "utf8");
assert.ok(bundle.length > 5e5);
assert.ok(!/<script[^>]+https?:/.test(fs.readFileSync(path.join(root, "index.html"), "utf8")));
console.log("PASS: 12 seals; 3 spells; wrong sequence, expiry, cooldown, chakra recovery; GLB 2.0, 16-bone skin, 12 animation clips, normals, offline bundle.");
