// Offline diagnostic rasterization of the recorded game's actual geometry/transforms.
// This is a geometry preview, not a browser screenshot or shader validation.
const fs=require('node:fs'),path=require('node:path'),zlib=require('node:zlib');
const {draws}=require('./smoke.cjs');const width=1200,height=800,aspect=width/height;
const image=new Uint8Array(width*height*4),depth=new Float32Array(width*height);depth.fill(Infinity);
const clamp=(v,a=0,b=1)=>Math.max(a,Math.min(b,v)),mix=(a,b,t)=>a+(b-a)*t;
for(let y=0;y<height;y++)for(let x=0;x<width;x++){const u=x/width,v=1-y/height,d=Math.hypot((u-.72)*aspect,v-.67),glow=Math.exp(-d*6),disc=1-clamp((d-.046)/.002),t=Math.pow(v,.7);const c=[mix(.86,.36,t)+.22*glow,mix(.70,.49,t)+.13*glow,mix(.52,.49,t)+.06*glow];for(let k=0;k<3;k++)image[(y*width+x)*4+k]=clamp(mix(c[k],[1,.82,.54][k],disc*.85))*255;image[(y*width+x)*4+3]=255;}
function transform(m,p){return [0,1,2,3].map(r=>m[r]*p[0]+m[4+r]*p[1]+m[8+r]*p[2]+m[12+r]);}
function clip(poly){for(let plane=0;plane<6;plane++){const f=p=>plane<2?p[3]+(plane===0?1:-1)*p[0]:plane<4?p[3]+(plane===2?1:-1)*p[1]:p[3]+(plane===4?1:-1)*p[2];const out=[];for(let i=0;i<poly.length;i++){let a=poly[i],b=poly[(i+1)%poly.length],fa=f(a),fb=f(b);if(fa>=0)out.push(a);if((fa>=0)!==(fb>=0)){let t=fa/(fa-fb);out.push(a.map((v,k)=>mix(v,b[k],t)));}}poly=out;if(!poly.length)break;}return poly;}
function triangle(a,b,c,color){const toScreen=p=>[(p[0]/p[3]*.5+.5)*width,(.5-p[1]/p[3]*.5)*height,p[2]/p[3]];a=toScreen(a);b=toScreen(b);c=toScreen(c);const area=(b[0]-a[0])*(c[1]-a[1])-(b[1]-a[1])*(c[0]-a[0]);if(Math.abs(area)<.00001)return;const minX=Math.max(0,Math.floor(Math.min(a[0],b[0],c[0]))),maxX=Math.min(width-1,Math.ceil(Math.max(a[0],b[0],c[0]))),minY=Math.max(0,Math.floor(Math.min(a[1],b[1],c[1]))),maxY=Math.min(height-1,Math.ceil(Math.max(a[1],b[1],c[1])));for(let y=minY;y<=maxY;y++)for(let x=minX;x<=maxX;x++){const u=((b[0]-x-.5)*(c[1]-y-.5)-(b[1]-y-.5)*(c[0]-x-.5))/area,v=((c[0]-x-.5)*(a[1]-y-.5)-(c[1]-y-.5)*(a[0]-x-.5))/area,w=1-u-v;if(u<0||v<0||w<0)continue;const z=u*a[2]+v*b[2]+w*c[2],index=y*width+x;if(z>=depth[index])continue;depth[index]=z;for(let k=0;k<3;k++)image[index*4+k]=clamp(color[k])*255;}}
let isHand=false;for(const draw of draws){if(draw.eye.every(x=>x===0)&&!isHand){depth.fill(Infinity);isHand=true;}const m=draw.model,vp=draw.vp,data=draw.data;for(let i=0;i<data.length;i+=18){let world=[],points=[];for(let j=0;j<3;j++){let offset=i+j*6,p=transform(m,[data[offset],data[offset+1],data[offset+2]]);world.push(p);points.push(transform(vp,p));}const n=[0,1,2].map(k=>m[k]*data[i+3]+m[4+k]*data[i+4]+m[8+k]*data[i+5]);const length=Math.hypot(...n);const light=Math.max(0,(-.45*n[0]+.8*n[1]+.35*n[2])/(length*Math.hypot(-.45,.8,.35)));const center=[0,1,2].map(k=>(world[0][k]+world[1][k]+world[2][k])/3),distance=Math.hypot(...center.map((v,k)=>v-draw.eye[k])),fog=(1-Math.exp(-distance*.010))*(1-draw.emission*.75),ft=clamp((center[1]+2)/35),color=draw.color.map((v,k)=>{const shade=mix(v*([.42,.44,.43][k]+light*[.69,.50,.30][k]),v*1.35,draw.emission);const fogColor=mix([.67,.59,.49][k],[.90,.66,.48][k],ft);return mix(shade,fogColor,fog);});const poly=clip(points);for(let j=1;j<poly.length-1;j++)triangle(poly[0],poly[j],poly[j+1],color);}}
function crc(bytes){let c=0xffffffff;for(const b of bytes){c^=b;for(let i=0;i<8;i++)c=(c>>>1)^((c&1)?0xedb88320:0);}return(c^0xffffffff)>>>0;}
function chunk(type,data){const t=Buffer.from(type),length=Buffer.alloc(4),sum=Buffer.alloc(4);length.writeUInt32BE(data.length);sum.writeUInt32BE(crc(Buffer.concat([t,data])));return Buffer.concat([length,t,data,sum]);}
const header=Buffer.alloc(13);header.writeUInt32BE(width);header.writeUInt32BE(height,4);header[8]=8;header[9]=6;const rows=Buffer.alloc((width*4+1)*height);for(let y=0;y<height;y++)rows.set(image.subarray(y*width*4,(y+1)*width*4),y*(width*4+1)+1);fs.writeFileSync(path.join(__dirname,'../world-preview.png'),Buffer.concat([Buffer.from([137,80,78,71,13,10,26,10]),chunk('IHDR',header),chunk('IDAT',zlib.deflateSync(rows)),chunk('IEND',Buffer.alloc(0))]));
console.log('Saved geometry diagnostic to world-preview.png');
